CREATE TABLE [dbo].[BP_MotorRequests]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Title] VARCHAR(100) not null,
    [FirstName] VARCHAR(100) not null,
    [Surname] VARCHAR(100) not null,
    [Email] VARCHAR(100) not null,
    [Mobile] VARCHAR(100) not null,
    [Dob] Date not null,
    [Gender] VARCHAR(100) not null,
    [Occupation] VARCHAR(100) not null,
    [Address] VARCHAR(100) not null,
    [State] VARCHAR(100) not null,
    [IdentificationType] VARCHAR(100) not null,
    [IdentificationNumber] VARCHAR(100) not null,
    [IdUpload] VARCHAR(100) not null,
    [IdUploadUrl] VARCHAR(100) not null,
    [TypeOfCover] VARCHAR(100) not null,
    [VehicleCategory] VARCHAR(100) not null,
    [VehicleValue] Int,
    [PaymentOption] VARCHAR(100) not null,
    [VehicleMake] VARCHAR(100) not null,
    [ModelOfVehicle] VARCHAR(100) not null,
    [RegistrationNumber] VARCHAR(100) not null,
    [ChasisNumber] VARCHAR(100) not null,
    [EngineNumber] VARCHAR(100) not null,
    [YearOfMake] VARCHAR(100) not null,
    [InsuranceStartDate] Date,
    [VehicleColor] VARCHAR(100) not null,
    [TotalCost] Int,
    [DateCreated] DateTime
)
