CREATE TABLE [dbo].[BP_Requests]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[RequestId] VARCHAR(10) not null,
	[BrokerId] VARCHAR(100) not null,
	[ProductId] Int not null,
    [PackageId] Int not null,
    [TypeOfUsage] VARCHAR(100),   
	[InsuredName] VARCHAR(100) not null,
    [Occupation] VARCHAR(100),
    [EmailAddress] VARCHAR(100),
    [TypeOfCover] VARCHAR(100) not null,
    [Mobile] VARCHAR(100),
    [Address] VARCHAR(100),
    [VehicleMake] VARCHAR(100),
    [YearOfMake] VARCHAR(4),
    [InsuranceStartDate] DateTime,
    [VehicleValue] Decimal,
    [InsuredValue] Decimal,
    [ModeOfPayment] VARCHAR(100),
    [PolicyHolder] VARCHAR(100) not null,
    [RegistrationNumber] VARCHAR(100),
    [CoverPeriod] INT not null,
    [PremiumRate] Int,
    [Premium] Decimal Not Null,
    [IdUploadUrl] VARCHAR(100),
    [UtilityBillUploadUrl] VARCHAR(100),
    [VehicleLicenseUploadUrl] VARCHAR(100),
    [BuildingLocation] VARCHAR(100),
    [BuildingValue] Decimal,
    [BuldingPurpose] VARCHAR(100),
    [DateCreated] DateTime

)
